Boucle globale de lecture de vidéo


state= 0
    img_calibration
    obstacle detection
    start and goal
    global_nav
    
state = 1
    img_calibration
    detect Thymio
    astolfi ou local nav
    
    

In [ ]:
#lancer la communication asynchrone avec thymio
from tdmclient import ClientAsync, aw
client = ClientAsync()
node = await client.wait_for_node()
await node.lock()

#vérifier d'avoir installer pyserial

# Initialisation

In [1]:
#check each import if it's really necessary
import cv2 
import time
import numpy as np
from PIL import Image 
import math
import matplotlib
from matplotlib.pyplot import imshow
from matplotlib import pyplot as plt

#import from global control
#import from glocal + control
import pyvisgraph as vg
import geopandas as gpd
from geopandas import GeoSeries
from shapely.geometry import Polygon, Point, LineString
import time

In [2]:
import Vision as vis
import Global as glob
import control as ctrl

In [3]:
#pour le test utilise une image mais en vrai relier à la caméra et temps réel

#img_final = np.array(Image.open('env_final.jpeg'))
img_final = cv2.imread('env_final.jpeg')
img_final2 = cv2.cvtColor(img_final, cv2.COLOR_BGR2RGB)
img=vis.img_calibration(img_final2)
#cv2.imwrite('warpped.png', zzz)

In [4]:
#obstacle detection
polygons=vis.obstacle_detection(img)

#Start and goal detection
start=vis.detectCircle(img,'cyan')

[[[1016  127]]

 [[1024  127]]

 [[1030  129]]

 [[1037  138]]

 [[1036  149]]

 [[1030  155]]

 [[1024  158]]

 [[1013  156]]

 [[1008  151]]

 [[1005  145]]

 [[1007  135]]

 [[1013  128]]]


In [ ]:
#plot the visibility graph

#a voir si on le met dedans
margin = 0.2
path=glob.global_pathplanning(start, goal, obst,margin)


